name: Google Cloud Run CI
on:
  pull_request:
    branches: [ $default-branch ]
    types: 
      - closed
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  
jobs:
  build:
    name: Build node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install
        run: npm clean-install
      
      - name: Build
        run: npm run-script build:ci
      
      - name: Test
        run: npm run-script test:ci
      
      - name: Archive build
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: dist
      
      - name: Archive code coverage
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: deploy_coverage
          path: coverage
  deploy:
    name: Deploy to Cloud Run
    if: ${{ github.event.pull_request.merged }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy_dist
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build & push container
        run: |-
          gcloud build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .
          gcloud push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        if: ${{ success() }}
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
        